-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM (SELECT c.CAR_ID as CAR_ID, c.CAR_TYPE as CAR_TYPE, ROUND((1-DISCOUNT_RATE*0.01)*DAILY_FEE*30) as FEE
      FROM CAR_RENTAL_COMPANY_CAR as c
      JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as d
      ON c.CAR_TYPE=d.CAR_TYPE
      WHERE c.CAR_TYPE IN ('세단', 'SUV')
      AND d.DURATION_TYPE = '30일 이상'
      AND c.CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE END_DATE >= '2022-11-01'
          AND START_DATE < '2022-12-01')) as f
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE desc, CAR_TYPE asc, CAR_ID desc;